### PR TITLE
Dependency version of cordova-plugin-add-swift-support increased

### PR DESCRIPTION
**Pull request by esskar**
addresses #5 and #8

### CODE REVIEW

**Comment by emcniece** [comment]
Awesome, thank you so much! Have you tested this by chance?

**Comment by esskar** [comment]
I sure did

**Comment by esskar** [comment]
I added code for mac and ip address

**Review by emcniece — APPROVED** [review]
Nice work! Thanks for the contributions.

**Comment by esskar** [comment]
Thanks for the merge. May i ask you to publish to npm?

**Comment by emcniece** [comment]
Wow, I completely forgot about that, I'm so sorry! Yes I'll publish today. 🙇

**Pull request merged**
